# Generated by Django 4.2.2 on 2025-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosurvey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('security_needs', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
